name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  publish:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4
        with:
          repository: sydjango-org/sydjango
          ref: master
          submodules: true
          token: ${{ secrets.PAT }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git submodule update --init --remote
          git commit -am "Website content updated"
          git push origin master
